/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RideRouteImport } from './routes/ride'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ShuttleTrackingRouteImport } from './routes/shuttle.tracking'
import { Route as ShuttleTicketRouteImport } from './routes/shuttle.ticket'
import { Route as ShuttleServiceRouteImport } from './routes/shuttle.service'
import { Route as ShuttleSeatsRouteImport } from './routes/shuttle.seats'
import { Route as ShuttleScheduleRouteImport } from './routes/shuttle.schedule'
import { Route as ShuttlePickupRouteImport } from './routes/shuttle.pickup'
import { Route as ShuttlePaymentRouteImport } from './routes/shuttle.payment'
import { Route as ShuttlePassengerRouteImport } from './routes/shuttle.passenger'
import { Route as RideTrackingRouteImport } from './routes/ride.tracking'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthOtpRouteImport } from './routes/auth.otp'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AdminVehiclesRouteImport } from './routes/admin.vehicles'
import { Route as AdminSchedulesRouteImport } from './routes/admin.schedules'
import { Route as AdminPickupPointsRouteImport } from './routes/admin.pickup-points'
import { Route as AdminOperationsRouteImport } from './routes/admin.operations'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as ShuttlePickupPointIdRouteImport } from './routes/shuttle.pickup.$pointId'

const RideRoute = RideRouteImport.update({
  id: '/ride',
  path: '/ride',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ShuttleTrackingRoute = ShuttleTrackingRouteImport.update({
  id: '/shuttle/tracking',
  path: '/shuttle/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const ShuttleTicketRoute = ShuttleTicketRouteImport.update({
  id: '/shuttle/ticket',
  path: '/shuttle/ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const ShuttleServiceRoute = ShuttleServiceRouteImport.update({
  id: '/shuttle/service',
  path: '/shuttle/service',
  getParentRoute: () => rootRouteImport,
} as any)
const ShuttleSeatsRoute = ShuttleSeatsRouteImport.update({
  id: '/shuttle/seats',
  path: '/shuttle/seats',
  getParentRoute: () => rootRouteImport,
} as any)
const ShuttleScheduleRoute = ShuttleScheduleRouteImport.update({
  id: '/shuttle/schedule',
  path: '/shuttle/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ShuttlePickupRoute = ShuttlePickupRouteImport.update({
  id: '/shuttle/pickup',
  path: '/shuttle/pickup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShuttlePaymentRoute = ShuttlePaymentRouteImport.update({
  id: '/shuttle/payment',
  path: '/shuttle/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ShuttlePassengerRoute = ShuttlePassengerRouteImport.update({
  id: '/shuttle/passenger',
  path: '/shuttle/passenger',
  getParentRoute: () => rootRouteImport,
} as any)
const RideTrackingRoute = RideTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => RideRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/auth/otp',
  path: '/auth/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVehiclesRoute = AdminVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchedulesRoute = AdminSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPickupPointsRoute = AdminPickupPointsRouteImport.update({
  id: '/pickup-points',
  path: '/pickup-points',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOperationsRoute = AdminOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const ShuttlePickupPointIdRoute = ShuttlePickupPointIdRouteImport.update({
  id: '/$pointId',
  path: '/$pointId',
  getParentRoute: () => ShuttlePickupRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookings': typeof BookingsRoute
  '/ride': typeof RideRouteWithChildren
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/pickup-points': typeof AdminPickupPointsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/ride/tracking': typeof RideTrackingRoute
  '/shuttle/passenger': typeof ShuttlePassengerRoute
  '/shuttle/payment': typeof ShuttlePaymentRoute
  '/shuttle/pickup': typeof ShuttlePickupRouteWithChildren
  '/shuttle/schedule': typeof ShuttleScheduleRoute
  '/shuttle/seats': typeof ShuttleSeatsRoute
  '/shuttle/service': typeof ShuttleServiceRoute
  '/shuttle/ticket': typeof ShuttleTicketRoute
  '/shuttle/tracking': typeof ShuttleTrackingRoute
  '/admin/': typeof AdminIndexRoute
  '/shuttle/pickup/$pointId': typeof ShuttlePickupPointIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bookings': typeof BookingsRoute
  '/ride': typeof RideRouteWithChildren
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/pickup-points': typeof AdminPickupPointsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/ride/tracking': typeof RideTrackingRoute
  '/shuttle/passenger': typeof ShuttlePassengerRoute
  '/shuttle/payment': typeof ShuttlePaymentRoute
  '/shuttle/pickup': typeof ShuttlePickupRouteWithChildren
  '/shuttle/schedule': typeof ShuttleScheduleRoute
  '/shuttle/seats': typeof ShuttleSeatsRoute
  '/shuttle/service': typeof ShuttleServiceRoute
  '/shuttle/ticket': typeof ShuttleTicketRoute
  '/shuttle/tracking': typeof ShuttleTrackingRoute
  '/admin': typeof AdminIndexRoute
  '/shuttle/pickup/$pointId': typeof ShuttlePickupPointIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookings': typeof BookingsRoute
  '/ride': typeof RideRouteWithChildren
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/pickup-points': typeof AdminPickupPointsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/ride/tracking': typeof RideTrackingRoute
  '/shuttle/passenger': typeof ShuttlePassengerRoute
  '/shuttle/payment': typeof ShuttlePaymentRoute
  '/shuttle/pickup': typeof ShuttlePickupRouteWithChildren
  '/shuttle/schedule': typeof ShuttleScheduleRoute
  '/shuttle/seats': typeof ShuttleSeatsRoute
  '/shuttle/service': typeof ShuttleServiceRoute
  '/shuttle/ticket': typeof ShuttleTicketRoute
  '/shuttle/tracking': typeof ShuttleTrackingRoute
  '/admin/': typeof AdminIndexRoute
  '/shuttle/pickup/$pointId': typeof ShuttlePickupPointIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/bookings'
    | '/ride'
    | '/admin/bookings'
    | '/admin/operations'
    | '/admin/pickup-points'
    | '/admin/schedules'
    | '/admin/vehicles'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/register'
    | '/ride/tracking'
    | '/shuttle/passenger'
    | '/shuttle/payment'
    | '/shuttle/pickup'
    | '/shuttle/schedule'
    | '/shuttle/seats'
    | '/shuttle/service'
    | '/shuttle/ticket'
    | '/shuttle/tracking'
    | '/admin/'
    | '/shuttle/pickup/$pointId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/bookings'
    | '/ride'
    | '/admin/bookings'
    | '/admin/operations'
    | '/admin/pickup-points'
    | '/admin/schedules'
    | '/admin/vehicles'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/register'
    | '/ride/tracking'
    | '/shuttle/passenger'
    | '/shuttle/payment'
    | '/shuttle/pickup'
    | '/shuttle/schedule'
    | '/shuttle/seats'
    | '/shuttle/service'
    | '/shuttle/ticket'
    | '/shuttle/tracking'
    | '/admin'
    | '/shuttle/pickup/$pointId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/bookings'
    | '/ride'
    | '/admin/bookings'
    | '/admin/operations'
    | '/admin/pickup-points'
    | '/admin/schedules'
    | '/admin/vehicles'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/register'
    | '/ride/tracking'
    | '/shuttle/passenger'
    | '/shuttle/payment'
    | '/shuttle/pickup'
    | '/shuttle/schedule'
    | '/shuttle/seats'
    | '/shuttle/service'
    | '/shuttle/ticket'
    | '/shuttle/tracking'
    | '/admin/'
    | '/shuttle/pickup/$pointId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookingsRoute: typeof BookingsRoute
  RideRoute: typeof RideRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ShuttlePassengerRoute: typeof ShuttlePassengerRoute
  ShuttlePaymentRoute: typeof ShuttlePaymentRoute
  ShuttlePickupRoute: typeof ShuttlePickupRouteWithChildren
  ShuttleScheduleRoute: typeof ShuttleScheduleRoute
  ShuttleSeatsRoute: typeof ShuttleSeatsRoute
  ShuttleServiceRoute: typeof ShuttleServiceRoute
  ShuttleTicketRoute: typeof ShuttleTicketRoute
  ShuttleTrackingRoute: typeof ShuttleTrackingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ride': {
      id: '/ride'
      path: '/ride'
      fullPath: '/ride'
      preLoaderRoute: typeof RideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/shuttle/tracking': {
      id: '/shuttle/tracking'
      path: '/shuttle/tracking'
      fullPath: '/shuttle/tracking'
      preLoaderRoute: typeof ShuttleTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shuttle/ticket': {
      id: '/shuttle/ticket'
      path: '/shuttle/ticket'
      fullPath: '/shuttle/ticket'
      preLoaderRoute: typeof ShuttleTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shuttle/service': {
      id: '/shuttle/service'
      path: '/shuttle/service'
      fullPath: '/shuttle/service'
      preLoaderRoute: typeof ShuttleServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shuttle/seats': {
      id: '/shuttle/seats'
      path: '/shuttle/seats'
      fullPath: '/shuttle/seats'
      preLoaderRoute: typeof ShuttleSeatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shuttle/schedule': {
      id: '/shuttle/schedule'
      path: '/shuttle/schedule'
      fullPath: '/shuttle/schedule'
      preLoaderRoute: typeof ShuttleScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shuttle/pickup': {
      id: '/shuttle/pickup'
      path: '/shuttle/pickup'
      fullPath: '/shuttle/pickup'
      preLoaderRoute: typeof ShuttlePickupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shuttle/payment': {
      id: '/shuttle/payment'
      path: '/shuttle/payment'
      fullPath: '/shuttle/payment'
      preLoaderRoute: typeof ShuttlePaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shuttle/passenger': {
      id: '/shuttle/passenger'
      path: '/shuttle/passenger'
      fullPath: '/shuttle/passenger'
      preLoaderRoute: typeof ShuttlePassengerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ride/tracking': {
      id: '/ride/tracking'
      path: '/tracking'
      fullPath: '/ride/tracking'
      preLoaderRoute: typeof RideTrackingRouteImport
      parentRoute: typeof RideRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/auth/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vehicles': {
      id: '/admin/vehicles'
      path: '/vehicles'
      fullPath: '/admin/vehicles'
      preLoaderRoute: typeof AdminVehiclesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schedules': {
      id: '/admin/schedules'
      path: '/schedules'
      fullPath: '/admin/schedules'
      preLoaderRoute: typeof AdminSchedulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pickup-points': {
      id: '/admin/pickup-points'
      path: '/pickup-points'
      fullPath: '/admin/pickup-points'
      preLoaderRoute: typeof AdminPickupPointsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/operations': {
      id: '/admin/operations'
      path: '/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AdminOperationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/shuttle/pickup/$pointId': {
      id: '/shuttle/pickup/$pointId'
      path: '/$pointId'
      fullPath: '/shuttle/pickup/$pointId'
      preLoaderRoute: typeof ShuttlePickupPointIdRouteImport
      parentRoute: typeof ShuttlePickupRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminOperationsRoute: typeof AdminOperationsRoute
  AdminPickupPointsRoute: typeof AdminPickupPointsRoute
  AdminSchedulesRoute: typeof AdminSchedulesRoute
  AdminVehiclesRoute: typeof AdminVehiclesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminOperationsRoute: AdminOperationsRoute,
  AdminPickupPointsRoute: AdminPickupPointsRoute,
  AdminSchedulesRoute: AdminSchedulesRoute,
  AdminVehiclesRoute: AdminVehiclesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface RideRouteChildren {
  RideTrackingRoute: typeof RideTrackingRoute
}

const RideRouteChildren: RideRouteChildren = {
  RideTrackingRoute: RideTrackingRoute,
}

const RideRouteWithChildren = RideRoute._addFileChildren(RideRouteChildren)

interface ShuttlePickupRouteChildren {
  ShuttlePickupPointIdRoute: typeof ShuttlePickupPointIdRoute
}

const ShuttlePickupRouteChildren: ShuttlePickupRouteChildren = {
  ShuttlePickupPointIdRoute: ShuttlePickupPointIdRoute,
}

const ShuttlePickupRouteWithChildren = ShuttlePickupRoute._addFileChildren(
  ShuttlePickupRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  BookingsRoute: BookingsRoute,
  RideRoute: RideRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ShuttlePassengerRoute: ShuttlePassengerRoute,
  ShuttlePaymentRoute: ShuttlePaymentRoute,
  ShuttlePickupRoute: ShuttlePickupRouteWithChildren,
  ShuttleScheduleRoute: ShuttleScheduleRoute,
  ShuttleSeatsRoute: ShuttleSeatsRoute,
  ShuttleServiceRoute: ShuttleServiceRoute,
  ShuttleTicketRoute: ShuttleTicketRoute,
  ShuttleTrackingRoute: ShuttleTrackingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
